# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: |
    [Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"
    iwr -outf rustup-init.exe https://win.rustup.rs
  displayName: 'Download Rust'
- script: |
    PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
    rustup-init.exe -y --default-toolchain stable --default-host x86_64-pc-windows-msvc
    echo %PATH%
    rustc -vV
    cargo -vV
  displayName: 'Install Rust'
- script: |
    PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
    cd native
    cargo build --release
    cat ./target/release/build/mm2tracker-*/output
    ls -l ./target/release/mm2tracker.exe
    copy ./target/release/mm2tracker.exe ../mm2tracker.exe
  displayName: 'Build mm2tracker.exe'
- script: |
    PATH=%PATH%;%USERPROFILE%\\.cargo\\bin
    cd native
    cargo test --release
  displayName: 'Test mm2tracker.exe'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: index.html
    archiveType: 'zip'
    archiveFile: mm2tracker.zip
    replaceExistingArchive: true
    verbose: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: assets/*60.png
    archiveType: 'zip'
    archiveFile: mm2tracker.zip
    replaceExistingArchive: false
    verbose: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: assets/item*20*.png
    archiveType: 'zip'
    archiveFile: mm2tracker.zip
    replaceExistingArchive: false
    verbose: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: mm2tracker.exe
    archiveType: 'zip'
    archiveFile: mm2tracker.zip
    replaceExistingArchive: false
    verbose: true

