# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- powershell: |
    [Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"
    iwr -outf rustup-init.exe https://win.rustup.rs
    ./rustup-init.exe -y --default-toolchain stable --default-host x86_64-pc-windows-msvc 2>&1 | %{ "$_" }
    $env:PATH = "$env:PATH;${env:USERPROFILE}\.cargo\bin"
    rustc -vV
    cargo -vV
  displayName: 'Install rust'
