# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  PATH: %PATH%;%USERPROFILE%\\.cargo\\bin

steps:
- script: echo %PATH%
  displayName: 'Run a one-line script'

- powershell: |
    [Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"
    iwr -outf rustup-init.exe https://win.rustup.rs
  displayName: 'Download Rust'
- script: |
    rustup-init.exe -y --default-toolchain stable --default-host x86_64-pc-windows-msvc
    echo %PATH%
    rustc -vV
    cargo -vV
  displayName: 'Install Rust'