[package]
name = "mm2tracker"
version = "0.1.0"
authors = ["Jason Dagit <dagitj@gmail.com>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [ "std", "winuser", "libloaderapi", "commctrl", "uxtheme" ] }
